// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HoKU_M1WjL_j9OAtMndHsPpLv2i9rtc',
    appId: '1:25850438302:web:9a1f53b0e69aae5b04d18f',
    messagingSenderId: '25850438302',
    projectId: 'test-b28a2',
    authDomain: 'test-b28a2.firebaseapp.com',
    storageBucket: 'test-b28a2.appspot.com',
    measurementId: 'G-1CY7LR1C39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMrzYv9NgwmRJY5ZCzFZN_CjXtpH-qGEo',
    appId: '1:25850438302:android:8457a26026f40bfd04d18f',
    messagingSenderId: '25850438302',
    projectId: 'test-b28a2',
    storageBucket: 'test-b28a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQW2lH5KgSA6lUj2DFHVQiQu_nXz6ktV8',
    appId: '1:25850438302:ios:2fce4f19d6681a6c04d18f',
    messagingSenderId: '25850438302',
    projectId: 'test-b28a2',
    storageBucket: 'test-b28a2.appspot.com',
    iosClientId:
        '25850438302-e8nug2toe2d2csjqaafi2hm36f8b0kui.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQW2lH5KgSA6lUj2DFHVQiQu_nXz6ktV8',
    appId: '1:25850438302:ios:a56dcc32720cbd9a04d18f',
    messagingSenderId: '25850438302',
    projectId: 'test-b28a2',
    storageBucket: 'test-b28a2.appspot.com',
    iosClientId:
        '25850438302-4ef6dmopfujpo0k63pb7v27gg8022uii.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
