class TaskModel {
  String id;
  String title;
  String description;
  bool isDone;
  DateTime date;

  TaskModel(
      {required this.title,
      required this.description,
      this.id = "",
      required this.isDone,
      required this.date}); //id will be autoGenerated from firebase

  TaskModel.fromJson(
      Map<String, dynamic>
          json) //named constructor to convert from map tp object
      : this(
          id: json["id"],
          title: json["title"],
          description: json["description"],
          isDone: json["isDone"],
          date: DateTime.fromMillisecondsSinceEpoch(json["date"]),
        );

  Map<String, dynamic> toJson() {
    //function
    return {
      "id": id, //key of map and object
      "title": title,
      "description": description,
      "isDone": isDone,
      "date": date.millisecondsSinceEpoch,
    };
  }
}
